
idf_component_register(
  SRCS
    "noto_emoji_10.c"
    "roboto_mono_10.c"
    "roboto_mono_12.c"
    "roboto_mono_14.c"
    "roboto_mono_16.c"
    "roboto_mono_18.c"
    "roboto_mono_20.c"
    "roboto_mono_24.c"
    "roboto_mono_bold_10.c"
    "roboto_mono_bold_12.c"
    "roboto_mono_bold_14.c"
    "roboto_mono_bold_16.c"
    "roboto_mono_bold_18.c"
    "roboto_mono_bold_20.c"
    "roboto_mono_bold_24.c"
  INCLUDE_DIRS "."
  REQUIRES
    lvgl
)
